### ISSUE TITLE
[1.16.4] Loot Spawn Chance adjustments not working?

### ISSUE THREAD

**Issue by Teacyn** [Thelnfamous1/Dungeons-Gear#27]
I've been tinkering with this mod's loot chances to try and get a balance that won't crowd out other mods I'm using, and it seems like the base spawn chances for any given chest aren't working right. The chance for a Unique artifact to replace a Common one does seem to be (as setting it to 0% made them entirely stop appearing, while 5% made them very rare but still appear), but the actual base chance for them to spawn doesn't seem to. I set mineshaft chests to have a 1% chance of spawning an artifact at all, and yet I looted 4 mineshafts in a row and every single chest had at least one artifact, with most having two.

I've attached all the relevant files I can think of in this .zip
[dungeons_gear_report.zip](https://github.com/Thelnfamous1/Dungeons-Gear/files/5742502/dungeons_gear_report.zip)

**Comment by Thelnfamous1** [comment]
My browser just warned me that your file contains a virus/malware. Any way you can post what the config files contain in a Github gist or some other online page like pastebin?

**Comment by Teacyn** [comment]
...Odd, no clue why that happened. Anyway yeah, let me whip up a Gist real quick.

**Comment by Teacyn** [comment]
This should be it. https://gist.github.com/Teacyn/12ae46225e90cefb8a9302176e08e442

**Comment by Thelnfamous1** [comment]
Well let me state how the system is intended to work:

Every chest added to a pool (common, uncommon, rare, super rare) receives 1 common armor item and 1 common weapon item by default (this is not adjustable currently). You can adjust the chance for each item to be a unique item instead of common for that pool, as well as the chance for an artifact to spawn in that pool as well.

As far as I understand, the only issue you are having is the artifacts not listening to the config. Just to make sure, you are not adjusting any values in the middle of the game, correct?

**Comment by Teacyn** [comment]
Yes, I am. I think I was misunderstanding the config files. I was wanting to make it so that chests don't spawn with any weapons/armor at all the majority of the time, and it seems like you can't currently do that. I thought "artifact" was referring to any and all loot, so I was getting confused why even setting it to 1% I was getting weapons and armor in every single chest. I didn't realize it was only referring to the "usable" items. That explains it. Sorry for the inconvenience on this, I guess I'll just remove the loot pools entirely outside of the really rare ones.

**Comment by Thelnfamous1** [comment]
Ah okay. Artifact is any of the charm-like items that have a right-click action and get put on cooldown upon use.
