### ISSUE TITLE
Bee Enchantment crash

### ISSUE THREAD

**Issue by Banh-Bao** [Thelnfamous1/Dungeons-Gear#29]
Was fighting Illigers on a server when this happened
https://pastebin.com/NbLh67EK

**Comment by Thelnfamous1** [comment]
Oddly enough, I wrote a script to prevent exactly this kind of thing from happening, guess I recently broke it somehow. 

It's happening because the Bee's revenge target is getting set to nothing / non-existent, and the Bee's revenge AI is trying to check if the revenge target is on the same scoreboard team as itself. Since you can't check the scoreboard team for a non-existent being, the game crashes.

It should be relatively easy, just requires some debugging as to why the current fix is not preventing this from happening.

**Comment by No3371** [comment]
Would you mind updating the repo to latest version so that I can compile a jar that disable bee spawning for my own server for now?

**Comment by Thelnfamous1** [comment]
Latest version on Curseforge has fixed the issue.
