### ISSUE TITLE
[1.16.3] Crash when Resourceful Bees mod is present

### ISSUE THREAD

**Issue by bessiq** [Thelnfamous1/Dungeons-Gear#7]
Forge: 34.1.25
Resourceful Bees 1.16.3-0.5.5b (and 2 previous versions)
dungeons_gear-1.16.2+1.16.3-2.0.12.jar (and several previous versions)
logs: https://gist.github.com/bessiq/4530d87371be852324d74493fbd9d28b

Not sure which mod is at fault, as both mods work fine if the other is not enabled. I thought I'd post here first to see what you think. Basically, the game crashes during Forge early loading when these two mods are enabled together. I know you recently added some kind of bee functionality, which I assume might be conflicting with something RBees is trying to do.

Thanks for any help you can provide.

**Comment by Thelnfamous1** [comment]
This is their fault. They access transformed a method in an AI class called HurtByTarget, which all mobs that attack when provoked use, from private/protected to public. As I use a mixin for the same class to fix a glaring error inside that method, the mod loaded complains that I am making a public method private/protected in my mixin because Resourceful Bees made it public with their access transformer. 

They should reduce their access transform usage in general to prevent problems like this. It is especially heinous in this case as that method doesn’t need to be access transformed in the first place.

**Comment by bessiq** [comment]
Thanks for the reply. I am going to open an issue with them and reference this issue to save some typing if that's cool.

**Comment by Thelnfamous1** [comment]
Link them to this part of my code so they can see why there's an issue:
https://github.com/Thelnfamous1/Dungeons-Gear/blob/master/src/main/java/com/infamous/dungeons_gear/mixin/HurtByTargetGoalMixin.java
